BEGIN;

TRUNCATE TABLE
  e_tickets,
  booking_items,
  payments,
  refunds,
  cancellation_requests,
  bookings,
  event_cancellation_refund_audits,
  coupon_redemptions,
  coupon_usage_reservations,
  coupons,
  promotions,
  discount_reconciliation_logs,
  orphan_eb_discounts,
  cart_items,
  carts,
  ga_inventory_claims,
  seat_lock_audit_log,
  seats,
  venue_seat,
  group_discount_rules,
  show_slot_pricing_tier,
  show_slot_occurrence,
  show_slot,
  moderation_records,
  review_eligibility,
  reviews,
  event_catalog,
  venue,
  city,
  user_genre_preferences,
  user_settings,
  user_wallets,
  password_reset_tokens,
  refresh_tokens,
  users,
  preference_options,
  organization_auth,
  cancellation_policy_tiers,
  cancellation_policies,
  webhook_config,
  organization
RESTART IDENTITY CASCADE;

COMMIT;
